version: '3.7'
networks:
  default:
    name: test
services:
  database:
    image: mysql:8
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: app
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql/
  php:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: php
    depends_on:
      - database
    volumes:
      - .:/app
    extra_hosts:
      - host.docker.internal:host-gateway
  nginx:
    image: nginx:1.25.1
    container_name: nginx
    working_dir: /app
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - "./:/app"
    ports:
      - "8000:80"
    depends_on:
      - php
volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###